### ISSUE TITLE
TransformerTorchEncoder index error 

### ISSUE THREAD

**Issue by Kavan72** [jina-ai/jina-hub#1483]
encode.yml:-
```
!TransformerTorchEncoder
with:
  pooling_strategy: cls
  pretrained_model_name_or_path: distilbert-base-cased
metas:
  on_gpu: true
```
![image](https://user-images.githubusercontent.com/19048640/103218507-2e18a100-4941-11eb-9bde-306b6dd99587.png)
